networks:
    apvs:
services:
  receiver:
    build:
      dockerfile: receiver_Dockerfile
      context: ./
      args:
        timezone: ${TZ}
    image: aps_receiver
    container_name: aps_receiver
    restart: always
    ports:
       - "8080:8080"
    networks:
      - apvs
  executor:
    build: 
      dockerfile: executor_Dockerfile
      context: ./
      args:
        timezone: ${TZ}
    image: aps_executor
    container_name: aps_executor
    privileged: true
    restart: always
    networks:
      - apvs