networks:
    apvs:
services:
  receiver:
    build:
      dockerfile: receiver_Dockerfile
      context: ./
      args:
        timezone: ${TZ}
    image: apvs_receiver
    container_name: apvs_receiver
    restart: always
    ports:
       - "8080:8080"
    environment: 
      TZ: ${TZ}
    networks:
      - apvs